### ISSUE TITLE
Bundle as plugin when Kirby 2.3 is released

### ISSUE THREAD

**Issue by jenstornell** [afbora/Kirby-Tabs-Field#10]

**Comment by jenstornell** [comment]
2.3 has been released. :)

**Comment by afbora** [comment]
What can i do for this? :smile:

**Comment by dweidner** [comment]
One think could be to add a package.json file to allow installing your field via the new Kirby CLI. See the following page for more details: https://github.com/getkirby/cli#kirby-plugininstall

**Comment by jenstornell** [comment]
https://getkirby.com/docs/developer-guide/plugins/registry

**Comment by dweidner** [comment]
Well the extension registry would only make sense, if this "plugin" provides more functionality than a panel field, for example providing additional field methods. Users are supposed to install the files into `site/fields` and not into `site/plugins`. There is no need to use the extension registry here.

**Comment by jenstornell** [comment]
**I quote one of the crew members:**

https://forum.getkirby.com/t/multiselect-field/1213/19

> With the new registry in Kirby 2.3, I believe all third-party elements like fields, snippets, blueprints etc. should also be delivered wrapped as a plugin. This enables us to keep only custom elements that are rather specific to the project in site/fields, site/tags etc.

**Comment by afbora** [comment]
@dweidner @jenstornell Added https://github.com/afbora/Kirby-Tabs-Field/commit/72ce2eebb6480251e12832f2784ee486ee47c5ea

**Comment by dweidner** [comment]
Thank you for the reference, @jenstornell. I have to disagree though. I would expect fields to be in the `site/fields` folder regardless of the author of a field/plugin.

**Comment by afbora** [comment]
Specified as `type: kirby-field` in package.json

**Comment by jenstornell** [comment]
It seems like you have @dweidner on your side as he setup the package.json as field. I have not changed my mind about it tho.

**Comment by dweidner** [comment]
I think we should move the discussion to another issue: https://github.com/distantnative/field-multiselect/issues/18

**Comment by malvese** [comment]
When I try to install the plugin with Kirby's CLI I get this error:
`[RuntimeException]
Invalid Kirby Plugin Type`

**Comment by malvese** [comment]
This could be a CLI bug. I had forgotten, but I reported the [same issue in june](https://github.com/distantnative/field-multiselect/issues/19#issuecomment-244556713) for Multiselect.

**Comment by afbora** [comment]
@malvese Could you try with downloaded new version?

**Comment by malvese** [comment]
@afbora Sorry for the delay! I just tried and it now works fine :) Thanks!
