### ISSUE TITLE
Current tab background incorrect when inside modal (structure field, builder field)

### ISSUE THREAD

**Issue by louiswalch** [afbora/Kirby-Tabs-Field#17]
The current tab's background retains a light gray background color, even if the tab bar is being shown inside a structure field or builder field. See image.

![the_present_tense___panel](https://cloud.githubusercontent.com/assets/286013/21489517/83663dd4-cbb9-11e6-98df-2f270d8a08b5.png)

**Comment by medienbaecker** [comment]
I've fixed that issue in a [pull request](https://github.com/afbora/Kirby-Tabs-Field/pull/18).
