### ISSUE TITLE
Not working in Kirby 2.2

### ISSUE THREAD

**Issue by ivi-admin** [afbora/Kirby-Tabs-Field#2]
The tabs plugin doesn't seem to be loading correctly in Kirby 2.2 -- it's just displaying as a checkbox field.

![image](https://cloud.githubusercontent.com/assets/8458490/11351373/49dd35bc-9204-11e5-8f89-9442cacb27a6.png)

Some plugins/fields broke with the 2.2 update or started to collide with each other, but this was still happening after removing all other plugins and fields. Maybe something with the way custom fields' JS gets loaded in 2.2.x?

**Comment by afbora** [comment]
Fixed https://github.com/afbora/Kirby-Tabs-Field/pull/3
