### ISSUE TITLE
Does not work with Kirby 2.5.4

### ISSUE THREAD

**Issue by benjigreig** [afbora/Kirby-Tabs-Field#21]
The plugin prevents Kirby from running. I was unable even to see any PHP errors. Happy to supply more detail if/when required.

**Comment by medienbaecker** [comment]
Are you sure this plugin is the reason? I use it too, and it works with Kirby 2.5.4.
There is a nasty bug in this Kirby version, preventing any page with a structure or builder field from working: https://github.com/getkirby/panel/issues/1080

**Comment by benjigreig** [comment]
Yeah am pretty sure. I've just followed the work-around for that bug until 2.5.5 is released. I'll put the plugin back in and see if it works now. Apologies if that is the case. Only became aware of that Structure bug last night.

**Comment by benjigreig** [comment]
Just tried it and yep same thing happens. I get a `HTTP ERROR 500` when I refresh post adding the plugin. This is on a fresh copy of Kirby with just the structure field fixes from the development branch. Have tested out the structure changes and they all seem to be behaving themselves now. As I have zero experience with this plugin I can't give you much more than what I'm trying with a fresh copy of Kirby. Any suggestions am happy to give them a go.

**Comment by medienbaecker** [comment]
I just downloaded a fresh starterkit of Kirby 2.5.4 and put the `tabs` folder into `site/fields`.
I do not get any errors, but can you try to set `c::set('debug', true);` in your `config.php`?

**Comment by maxxscho** [comment]
I get the Fatal Error
`Class 'BaseField' not found in /my/path/to/kirby/site/plugins/tabs/tabs.php on line 3` on Kirby 2.5.4

**Comment by maxxscho** [comment]
Ok, this was my fault. I put it in the plugins folder. Sorry 😅
