### ISSUE TITLE
Installation > Would be great to get a short install guide

### ISSUE THREAD

**Issue by StefanEndress** [afbora/Kirby-Tabs-Field#25]
Thanks!

**Comment by mciszczon** [comment]
__With Kirby CLI:__

```bash
$ cd /your/kirby/installation
$ kirby plugin:install afbora/Kirby-Tabs-Field
```

__With Git:__

```bash
$ cd /your/kirby/instalation/site/plugins
$ git clone https://github.com/afbora/Kirby-Tabs-Field.git
```

__Tarball__

Simply [download this repository](https://github.com/afbora/Kirby-Tabs-Field/archive/master.zip) and extract it into `/your-kirby-installation/site/plugins/`.
