### ISSUE TITLE
Losing active tab after save

### ISSUE THREAD

**Issue by mearno** [afbora/Kirby-Tabs-Field#4]
First, great filed, just what I needed :)

I've got one little thing:

When I have a tab with a structured field and add or edit the field I end up at the first tab instead of staying on the active (third) tab where the structured field is.

It would be nice to stay on the active tab after adding structured fields or even after a general page save.

**Comment by afbora** [comment]
Fixed https://github.com/afbora/Kirby-Tabs-Field/pull/5
