### ISSUE TITLE
First field stays focused on other tab

### ISSUE THREAD

**Issue by medienbaecker** [afbora/Kirby-Tabs-Field#8]
When reloading the panel, the last opened tab will reopen. Unfortunately the first field (title) will be focused. So you can edit the field by mistake. For example when using keyboard shortcuts.

To showcase it, I switched to the second tab, reloaded and typed "asdf":
![focused-title](https://cloud.githubusercontent.com/assets/7975568/14943067/a501a204-0fcf-11e6-9e82-2e740fcfcfec.gif)

**Comment by medienbaecker** [comment]
I just played around with the [relevant lines of tabs.js](https://github.com/afbora/Kirby-Tabs-Field/blob/master/assets/js/tabs.js#L65-L68) and added two lines that focus the **first input of the active tab**: https://github.com/medienbaecker/Kirby-Tabs-Field/commit/a0ed17f6fad1b890863860eff3896cf65b42bf08

**Comment by afbora** [comment]
Thanks @medienbaecker
